### ISSUE TITLE
[Suggestion] Potions/Armor

### ISSUE THREAD

**Issue by Drakoflame** [DenisMasterHerobrine/Lava-Industries#2]
I know it's not the most original thing suggesting armor, but it would kinda work for how you do get the lava coal. 

Rather than just making the armor out of coal, maybe have some sort of recipe with 8 of the lava coal around a diamond/iron/gold to create a lava infused gem/ingot, which can do 1024 operations, but can also be crafted into a full set of armor. When crafted they come with innate fire protection, or, when worn as a full set, gives a permanent fire resistance potion buff. 

As well, you could make fire resistance potions from using the lavacoal in a brewing stand.

**Comment by DenisMasterHerobrine** [comment]
Seems to be an interesting idea, I was thinking about armor, had to implement it in 1.13, but because Forge for 1.13 is not ready, and I want to add content for Lava Industries, so I'll add something like gem or infused ingot and armor with fire resistance when full set is equipped.

**Comment by DenisMasterHerobrine** [comment]
Sorry for very **long** delay, added in 1.0.5, enjoy. :)
